name: Deploy Python to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: 'glucko-track-prod'
  GAR_LOCATION: 'europe-central2'
  REPOSITORY: 'glucko-repository'
  IMAGE: 'python-be'
  GKE_CLUSTER: 'autopilot-glucko-cluster'
  GKE_ZONE: 'europe-central2'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: 'github-actions-deployer@glucko-track-prod.iam.gserviceaccount.com'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Build and Push Python Image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} .
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/python-deployment.yaml
          kubectl apply -f k8s/python-service.yaml
          kubectl set image deployment/glucko-python python-be=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
          kubectl rollout status deployment/glucko-python